/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public String getGreeting() {
        return "Hello world.";
    }


    //define an interface type.Actually this is a functional interface. A Functional interface will only have one method.
    interface Add {
        double add(double n1, double n2);
    }

    interface Print {
        void m();
    }

    interface PrintString {
        void print(String s);
    }


    public static void main(String[] args) {

        //Assign method/behaviour to a variable.What compiler does is checking the lambda expression signature against the Add interface method signature.
        Add add = (double n1, double n2) -> {
            return n1 + n2;
        };

        Print print = () -> {
            System.out.println("Hi Java 8");
        };

        //type inference rocks!!!!
        PrintString printString = s -> System.out.println(s);

        //passing the behaviours to a functions.
        add(add);
        print(s -> System.out.println(s));


        //direct executions.
        System.out.println(add.add(12.34, 56.23));
        print.m();
        printString.print("Hi Dasun !!!!");

    }

    public static void add(Add add) {
        System.out.println(add.add(12, 45.89));
    }

    public static void print(PrintString printString) {
        String s = "hey";
        printString.print(s);
    }


}
