/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public String getGreeting() {
        return "Hello world.";
    }


    //define an interface type

    interface Add {
        double add(double n1, double n2);
    }

    public static void main(String[] args) {

        //Assign method/behaviour to a variable
        Add add = (double n1, double n2) -> {
            return n1 + n2;
        };

        System.out.println(add.add(12.34, 56.23));
    }
}
